window.FincontrolLayout = (() => {
  function initials(user) { return String(user?.name || "FC").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
  function link(active, href, icon, label) { return `<a class="nav-link ${active ? "active" : ""}" href="${href}"><i class="fas fa-${icon} fa-fw"></i><span>${label}</span></a>`; }
  function buildSidebar(user, activePage) {
    return `<div class="sidebar-inner"><a class="navbar-brand sidebar-brand" href="/dashboard"><span class="sidebar-brand-mark">FC</span><span><strong>Fincontrol</strong><small>IA Financeira</small></span></a><hr class="sidebar-divider"><nav class="reference-nav">
      ${link(activePage === "dashboard", "/dashboard", "tachometer-alt", "Dashboard")}
      <div class="sidebar-section-label">Finanças</div>
      ${link(false, "#summary-cards", "exchange-alt", "Movimentações")}${link(false, "#summary-cards", "arrow-down", "Gastos")}${link(false, "#summary-cards", "arrow-up", "Receitas")}${link(false, "#summary-cards", "file-invoice-dollar", "Faturas")}${link(false, "#goals-list", "bullseye", "Metas")}${link(false, "#cash-flow-chart", "chart-bar", "Gráficos")}
      <div class="sidebar-section-label">Atendimento</div>
      ${link(false, "#ai-summary", "file-alt", "Relatórios")}${link(false, "#reminders-list", "bell", "Lembretes")}${link(false, "#ai-summary", "comments", "Conversas da IA")}
    </nav><div class="sidebar-footer"><a class="nav-link ${activePage === "settings" ? "active" : ""}" href="/configuracoes"><i class="fas fa-cog fa-fw"></i><span>Configurações</span></a><button id="sidebar-logout" class="btn sidebar-logout" type="button"><i class="fas fa-sign-out-alt fa-fw"></i><span>Sair</span></button><div class="sidebar-user"><span class="avatar">${initials(user)}</span><div><strong>${window.FincontrolUtils.escapeHtml(user?.name || "Usuário")}</strong><small>${window.FincontrolUtils.escapeHtml(user?.email || user?.phone || "Conta Fincontrol")}</small></div></div></div></div>`;
  }
  function buildTopbar(user, period) {
    return `<div class="container-fluid reference-topbar-inner"><button id="sidebar-toggle" class="mobile-menu-button btn btn-link" type="button" aria-label="Abrir menu" aria-expanded="false"><i class="fas fa-bars"></i></button><label class="topbar-search"><i class="fas fa-search"></i><input type="search" placeholder="Buscar no painel" aria-label="Buscar no painel"></label><div class="topbar-actions ml-auto"><label class="period-select"><span>Período</span><select id="period-select" aria-label="Selecionar período"><option value="current_month" ${period === "current_month" ? "selected" : ""}>Mês atual</option><option value="previous_month" ${period === "previous_month" ? "selected" : ""}>Mês passado</option><option value="current_week" ${period === "current_week" ? "selected" : ""}>Esta semana</option><option value="current_year" ${period === "current_year" ? "selected" : ""}>Este ano</option><option value="today" ${period === "today" ? "selected" : ""}>Hoje</option></select></label><button id="refresh-dashboard" class="icon-button" type="button" aria-label="Atualizar"><i class="fas fa-sync-alt"></i></button><button class="icon-button" type="button" aria-label="Notificações"><i class="fas fa-bell"></i></button><span class="avatar topbar-avatar">${initials(user)}</span></div></div>`;
  }
  async function renderShell(user, period, onPeriodChange, onLogout) {
    const sidebar = document.getElementById("sidebar"); const topbar = document.getElementById("topbar"); const active = window.location.pathname.includes("configuracoes") ? "settings" : "dashboard";
    if (sidebar) sidebar.innerHTML = buildSidebar(user, active); if (topbar) topbar.innerHTML = buildTopbar(user, period);
    const toggle = document.getElementById("sidebar-toggle"); const backdrop = document.getElementById("sidebar-backdrop"); const close = () => { document.body.classList.remove("sidebar-open"); if (backdrop) backdrop.hidden = true; toggle?.setAttribute("aria-expanded", "false"); };
    toggle?.addEventListener("click", () => { const open = !document.body.classList.contains("sidebar-open"); document.body.classList.toggle("sidebar-open", open); if (backdrop) backdrop.hidden = !open; toggle.setAttribute("aria-expanded", String(open)); }); backdrop?.addEventListener("click", close); sidebar?.querySelectorAll("a").forEach((a) => a.addEventListener("click", close)); document.getElementById("period-select")?.addEventListener("change", (event) => onPeriodChange?.(event.target.value)); document.getElementById("sidebar-logout")?.addEventListener("click", onLogout); document.getElementById("refresh-dashboard")?.addEventListener("click", () => document.dispatchEvent(new CustomEvent("fincontrol:refresh")));
  }
  return { renderShell };
})();
